### ISSUE TITLE
Despite readonly is true for metadata field list entries can be deleted

### ISSUE THREAD

**Issue by majosch** [opencast/opencast-editor#641]
I tried to make the metadata field `creator` readonly:

```toml
[metadata]
show = true

[metadata.configureFields."EVENTS.EVENTS.DETAILS.CATALOG.EPISODE"]
title = {show = true, readonly = false}
creator = {show = true, readonly = true}
[...]
```
also see: https://editor.oc.univie.ac.at/editor-settings.toml

As expected no new users can be added to the creators list, but it's allowed to remove existing entries. I guess this is not the intended behaviour?
